<?php
/**
 * Plugin Name: Simple Header & Footer Scripts
 * Plugin URI: http://johnregan3.github.io/simple-header-footer-scripts
 * Description: The simple, solid way to add custom scripts to your WordPress website. Simple Header & Footer Scripts allows you to add your own scripts (including Google Analytics) to your header or footer regardless of what theme you are using.</p>
 * Author: John Regan
 * Author URI: http://johnregan3.me
 * Version: 1.0
 * Text Domain: shfs
 *
 * Copyright 2013  John Regan  (email : johnregan3@outlook.com)
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 2, as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 *
 * @package SHFS
 * @author John Regan
 * @version 1.0
 */


/**
 * Print direct link to Simple Header & Footer Scripts admin page
 *
 * Fetches array of links generated by WP Plugin admin page ( Deactivate | Edit )
 * and inserts a link to the Custom CSS admin page
 *
 * @since  1.0
 * @param  array $links Array of links generated by WP in Plugin Admin page.
 * @return array        Array of links to be output on Plugin Admin page.
 */
function shfs_settings_link( $links ) {
	$settings_page = '<a href="' . admin_url('tools.php?page=simple-header-footer-scripts.php' ) .'">Settings</a>';
	array_unshift( $links, $settings_page );
	return $links;
}

$plugin = plugin_basename(__FILE__);

add_filter( "plugin_action_links_$plugin", 'shfs_settings_link' );

/**
 * Register text domain
 *
 * @since 1.0
 */
function shfs_textdomain() {
	load_plugin_textdomain('shfs');
}

add_action('init', 'shfs_textdomain');


/**
 * Delete Settings on Uninstall
 *
 * @since 1.0
 */
function shfs_uninstall() {
	unregister_setting( 'shfs_settings_group', 'shfs_settings' );
}

register_uninstall_hook( __FILE__, 'shfs_uninstall' );

/**
 * Print Header Scripts
 *
 * @since 1.0
 */
function shfs_header_scripts() {
	ob_start();
		$options = get_option( 'shfs_settings' );
		$sfhs_header = isset( $options['header_scripts_input'] ) ? $options['header_scripts_input'] : '';
		echo "<script type=text/javascript>";
		if ( isset( $options['shfs_credit'] ) ) {
			echo "/*
 * Rendered by the Simple Header & Footer Scripts Plugin
 * http://wordpress.org/plugins/simple-header-footer-scripts/
 */\n";
		}
		echo $sfhs_header;
		echo "</script>";
	echo ob_get_clean();
}

/**
 * Print Footer Scripts
 *
 * @since 1.0
 */
function shfs_footer_scripts() {
	ob_start();
		$options = get_option( 'shfs_settings' );
		$sfhs_footer = isset( $options['footer_scripts_input'] ) ? $options['footer_scripts_input'] : '';
		echo "<script type=text/javascript>";
		if ( isset( $options['shfs_credit'] ) ) {
			echo "/*
 * Rendered by the Simple Header & Footer Scripts Plugin
 * http://wordpress.org/plugins/simple-header-footer-scripts/
 */\n";
		}
		echo $sfhs_footer;
		echo "</script>";
	echo ob_get_clean();
}

/**
 * Attaches Scripts to Hooks to be rendered
 *
 * @since 1.0
 */
function shfs_render_scripts() {
	$options = get_option( 'shfs_settings' );
	if ( isset( $options['header_scripts_input'] ) )
		add_action( 'wp_head', 'shfs_header_scripts' );

	if ( isset( $options['footer_scripts_input'] ) )
		add_action( 'wp_footer', 'shfs_footer_scripts' );
}

add_action( 'init', 'shfs_render_scripts' );

/**
 * Register "Header/Footer Scripts" submenu in "Tools" Admin Menu
 *
 * @since 1.0
 */
function shfs_register_submenu_page() {
	add_management_page( __( 'Simple Header & Footer Scripts', 'shfs' ), __( 'Header/Footer Scripts', 'shfs' ), 'edit_themes', basename(__FILE__), 'shfs_render_submenu_page' );
}

add_action( 'admin_menu', 'shfs_register_submenu_page' );


/**
 * Register settings
 *
 * @since 1.0
 */
function shfs_register_settings() {
	register_setting( 'shfs_settings_group', 'shfs_settings' );

	add_settings_section( 'shfs_primary_section', __( '', 'rt_polls' ), 'shfs_primary_section_cb', __FILE__ );

	add_settings_field( 'shfs_header_scripts_input', __( 'Header Scripts', 'rt_polls' ), 'shfs_header_scripts_input', __FILE__, 'shfs_primary_section' );

	add_settings_field( 'shfs_footer_scripts_input', __( 'Footer Scripts', 'rt_polls' ), 'shfs_footer_scripts_input', __FILE__, 'shfs_primary_section' );

	add_settings_field( 'shfs_credit', __( 'This Plugin is Really Helpful!', 'rt_polls' ), 'shfs_credit', __FILE__, 'shfs_primary_section' );
}

add_action('admin_init', 'shfs_register_settings');

/**
 * Render Primary Section text
 *
 * @since  1.0
 */
function shfs_primary_section_cb() {}

/**
 * Render Header Scripts Input
 *
 * @since  1.0
 */
function shfs_header_scripts_input() {
	$options  = get_option('shfs_settings');
	$field_value   = isset( $options['header_scripts_input'] ) ? $options['header_scripts_input'] : ''; ?>
	<textarea id="header-scripts-input" name="shfs_settings[header_scripts_input]" placeholder="Header Scripts" style="width:300px; height: 200px;" ><?php echo esc_html( $field_value ) ?></textarea>
	<?php
}

/**
 * Render Footer Scripts Input
 *
 * @since  1.0
 */
function shfs_footer_scripts_input() {
	$options  = get_option('shfs_settings');
	$field_value   = isset( $options['footer_scripts_input'] ) ? $options['footer_scripts_input'] : ''; ?>
	<textarea id="footer-scripts-input" name="shfs_settings[footer_scripts_input]" placeholder="Footer Scripts" style="width:300px; height: 200px;" ><?php echo esc_html( $field_value ) ?></textarea>
	<?php
}

/**
 * Render Credit Author checkbox
 *
 * @since  1.0
 */
function shfs_credit() {
	$options = get_option('shfs_settings');
	$field_value = isset( $options['shfs_credit'] ) ? $options['shfs_credit'] : 0;
	?>
		<input type="checkbox" name="shfs_settings[shfs_credit]" value="1" <?php checked( 1, $field_value ) ?> />
		<p style="width: 300px;" class="description">
			<?php _e( 'Print credit to the author along with your script(s).  Nothing will be publicly visible on your site.', 'shfs' ) ?>
		</p>
	<?php
}

/**
 * Render Plugin submenu page
 *
 * @since 1.0
 */
function shfs_render_submenu_page() {

	if ( isset( $_GET['settings-updated'] ) ) : ?>
		<div id="message" class="updated"><p><?php _e( 'Scripts updated successfully.' ); ?></p></div>
	<?php endif; ?>
 
	<div class="wrap">
		<?php screen_icon(); ?>
		<h2><?php _e( 'Simple Header & Footer Scripts', 'shfs' ); ?></h2>
		<p><?php _e('Simple Header & Footer Scripts allows you to add your own scripts (including Google Analytics) to your header or footer regardless of what theme you are using.', 'shfs') ?></p>
		<form name="shfs-form" action="options.php" method="post" enctype="multipart/form-data">
			<?php settings_fields('shfs_settings_group'); ?>
			<?php do_settings_sections( __FILE__ ); ?>
			<p class="submit">
				<input name="scripts-submit" type="submit" class="button-primary" value="<?php esc_attr_e( 'Update Scripts', 'shfs' ); ?>" />
			</p>
		</form>
	</div>
	<?php
}
